### PR TITLE
Optimizing

### PR DESCRIPTION
**Pull request by mostafakavand**
Optimizing and fixing some bugs

### CODE REVIEW

**Comment by mostafakavand** [comment]
The latest version is supposed to be pushed by @Mohammadreza-Rokni

**Comment by BamdadTabari** [comment]
> The latest version is supposed to be pushed by @Mohammadreza-Rokni

I see some nice jobs like using the "map function", there is a question about why you used chunk?!  wasn't that unnecessary? this line and its above line, make code complicated. tell me why you use that.

**Comment by mostafakavand** [comment]
I don't know if I can explain this correctly or not
In this way, the generated passwords are stored in the short-term memory of the computer. And after reaching 1000 numbers, they are saved simultaneously in the output file.
This increases the speed of code execution

**Comment by mostafakavand** [comment]
Of course, you can run the program without it

**Comment by BamdadTabari** [comment]
> I don't know if I can explain this correctly or not In this way, the generated passwords are stored in the short-term memory of the computer. And after reaching 1000 numbers, they are saved simultaneously in the output file. This increases the speed of code execution

looks cool, but leave a comment for this in the source code. and remind me later to check the speed difference

**Review by BamdadTabari — COMMENTED** [review]
done

**Pull request merged**
